# Así aparece esta computadora en la red.
nombre = "korunix"

# "estable" cambia menos; "inestable" trae cosas más nuevas.
canal = "inestable"

[aplicaciones]
# Pon aquí las aplicaciones que quieres tener.
instaladas = [
  "firefox",
  "karere",
  "blender",
]
