{
  config,
  inputs,
  pkgs,
  ...
}: {
  # Lista de paquetes instalados en el perfil del sistema
  environment.systemPackages = with pkgs; [
    alacritty
    android-tools
    birdfont
    eog
    fastfetch
    figma-linux
    fontforge
    google-chrome
    heroic
    inputs.zen-browser.packages.${pkgs.stdenv.hostPlatform.system}.default
    kdePackages.kate
    kdePackages.kdenlive
    lutris
    nautilus
    nautilus-open-any-terminal
    onlyoffice-desktopeditors
    peazip
    polyglot
    protonplus
    rar
    scrcpy
    sunshine
    thunderbird
    unrar
    valent
    vesktop
    vlc
    vscode
    xwayland-satellite
    zoom-us
  ];
}
