{
  config,
  pkgs,
  ...
}: {
  # Lista de paquetes instalados en el perfil del sistema
  environment.systemPackages = with pkgs; [
    alacritty
    android-tools
    birdfont
    eog
    fastfetch
    figma-linux
    fontforge
    git
    google-chrome
    heroic
    just
    kdePackages.kate
    kdePackages.kdenlive
    lutris
    nautilus
    nautilus-open-any-terminal
    onlyoffice-desktopeditors
    peazip
    polyglot
    protonplus
    rar
    scrcpy
    sunshine
    thunderbird
    tree
    unrar
    valent
    vesktop
    vlc
    vscode
    wget
    xwayland-satellite
  ];
}
